[package]
name = "sketch_05_wave"
version = "0.1.0"
authors = ["kawadumax <kazmax7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.15.0"
audrey = "0.3"
nannou_audio = "0.15.0"
